version: "3.5"

services:
    node:
        build: server
        container_name: server
        depends_on:
            - mysqldb
        ports:
            - 3001:3001
        environment:
            - APP_NAME=MovieRecommendation
            - SERVER_ROOT=.
            - CHOKIDAR_USEPOLLING=true
        volumes:
            - ./server:/usr/src/app
            - /usr/src/app/node_modules

    react:
        build: client
        container_name: client
        environment:
            - CHOKIDAR_USEPOLLING=true
        volumes:
            - ./client:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - 3000:3000
      
    mysqldb:
        image: mysql
        container_name: db 
        restart: always
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        env_file:
            - "./server/.env"
        ports:
            - 3306:3306
        volumes:
            - ./db_data:/var/lib/mysql
