version: "3.5"

services:
#  node:
#    build: server
#    container_name: movie-server
#    depends_on:
#      - mysqldb
#    ports:
#      - 3001:3001
#    environment:
#      - APP_NAME=MovieRecommendation
#      - SERVER_ROOT=.
#      - CHOKIDAR_USEPOLLING=true
#    volumes:
#      - ./server:/usr/src/app
#      - /usr/src/app/node_modules

#  react:
#    build: client
#    container_name: movie-client
#    environment:
#      - CHOKIDAR_USEPOLLING=true
#    volumes:
#      - ./client:/usr/src/app
#      - /usr/src/app/node_modules
#    ports:
#      - 3000:3000
      
  mysqldb:
      image: mysql/mysql-server 
      container_name: movie-mysql 
      restart: always
      command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      env_file:
          - "./server/.env"
      ports:
          - "3306:3306"
      volumes:
          - "./data:/var/lib/mysql"
